@startuml
package "com.tupad.entities" {
  class FichaBibliografica {
    - id: Long
    - eliminado: boolean
    - isbn: String
    - clasificacionDewey: String
    - estanteria: String
    - idioma: String
    + getters/setters
    + toString()
  }

  class Libro {
    - id: Long
    - eliminado: boolean
    - titulo: String
    - autor: String
    - editorial: String
    - anioEdicion: Integer
    - ficha: FichaBibliografica
    + getters/setters
    + toString()
  }

  Libro --> "1" FichaBibliografica : 1..1 unidireccional
}
@enduml
